version: "3.9"
services:
  backend:
    build: ./backend
    command: ["python", "-m", "flask", "run", "-h", "0.0.0.0"]
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    command: ["python", "-m", "http.server"]
